<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Vortice.Vulkan" Version="3.2.3" />
    <PackageVersion Include="StbImageSharp" Version="2.30.15" />
    <PackageVersion Include="ppy.SDL3-CS" Version="2026.722.0" />
  </ItemGroup>
</Project>
