<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><AssemblyName>IsometricSandbox</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Engine.Core\Engine.Core.csproj" />
    <ProjectReference Include="..\..\src\Engine.Mathematics\Engine.Mathematics.csproj" />
    <ProjectReference Include="..\..\src\Engine.Ecs\Engine.Ecs.csproj" />
    <ProjectReference Include="..\..\src\Engine.Platform.Desktop\Engine.Platform.Desktop.csproj" />
    <ProjectReference Include="..\..\src\Engine.Rendering.Vulkan\Engine.Rendering.Vulkan.csproj" />
  </ItemGroup>
</Project>
