<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>Engine.Platform.Desktop</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Engine.Platform\Engine.Platform.csproj" />
    <ProjectReference Include="..\Engine.Platform.SDL3\Engine.Platform.SDL3.csproj" />
  </ItemGroup>
</Project>
