<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>Engine.Rendering.Vulkan</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Engine.Platform\Engine.Platform.csproj" />
    <ProjectReference Include="..\Engine.Rendering\Engine.Rendering.csproj" />
    <PackageReference Include="Vortice.Vulkan" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\assets\shaders\*.spv">
      <Link>shaders\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Import Project="ShaderCompile.targets" />
</Project>
